### PR TITLE
Improve the ColBERT implementation to use down-casting

### PR DESCRIPTION
**Pull request by bclavie**
Follow-up to https://github.com/hotchpotch/JQaRA/pull/7 @hotchpotch 

This PR takes into account the downcasting layer of ColBERT, which converts the BERT raw output (dim 768) to a smaller size (dim 128). The raw BERT output isn't actually trained as much, so a model that has learned enough should perform much better with the linear layer, since it's directly used in scoring!

The results do hold true, the less-learned models (v1 and v2) are actually weaker with the linear downcasting, most likely as they've not learned "enough" useful representation to make up for the lower dimensionality. However, for v2.4 and v2.5, the results are even better!

```
#    Model          NDCG@10    MRR@10    NDCG@100    MRR@100
---  -------------  ---------  --------  ----------  ---------
a    JaColBERT      0.549      0.812     0.731       0.814
b    JaColBERTv2    0.591ᵃ     0.832ᵃ    0.754ᵃ      0.834ᵃ
c    JaColBERTv2.4  0.627ᵃᵇ    0.856ᵃᵇ   0.777ᵃᵇ     0.857ᵃᵇ
d    JaColBERTv2.5  0.642ᵃᵇᶜ   0.864ᵃᵇᶜ  0.787ᵃᵇᶜ    0.866ᵃᵇᶜ
```

### CODE REVIEW

**Comment by hotchpotch** [comment]
Thank you for this PR!
I see now that the linear layer was necessary. Thank you for the correction!
It's great to see that the scores improve significantly with the latest models. Excellent work! 🎉 🎉 🎉

**Comment by hotchpotch** [comment]
While this is unrelated to the PR, I read your article:

https://www.answer.ai/posts/2024-08-13-small-but-mighty-colbert.html

It's an excellent article!
I'm currently in the process of pre-training a small parameter model for Japanese. I strongly resonate with your approach on the importance of small models.

**Comment by bclavie** [comment]
> While this is unrelated to the PR, I read your article:
> https://www.answer.ai/posts/2024-08-13-small-but-mighty-colbert.html
> It's an excellent article!

Thank you, this is very kind of you to say!

> I'm currently in the process of pre-training a small parameter model for Japanese. I strongly resonate with your approach on the importance of small models.

This is very exciting to hear! Are you training the base (MLM or RTD) model using distillation from a large BERT? If I can help you in any way, please let me know, I'd be happy to be involved!

**Comment by hotchpotch** [comment]
- https://huggingface.co/hotchpotch/mMiniLMv2-L6-H384
- https://huggingface.co/hotchpotch/mMiniLMv2-L12-H384

The approach I'm taking uses Microsoft's mMiniLMv2 (11M params for L6H384 or 33M params for L12H384) as a base, which is a distilled model of XLMRobertaLarge. While this model performs well as a multilingual model, its tokenizer isn't optimal for Japanese. To address this, I created a Japanese-specific tokenizer and merged the vocab weights accordingly.
Here's a simple method for merging weights (I've since optimized it further):

[Running XLMRobertaTokenizer trained on Japanese](https://scrapbox.io/hotchpotch/XLMRobertaTokenizer_%E3%82%92%E6%97%A5%E6%9C%AC%E8%AA%9E%E3%81%A7%E5%AD%A6%E7%BF%92%E3%81%95%E3%81%9B%E3%81%A6%E5%8B%95%E3%81%8B%E3%81%99) (apologies, it's in Japanese)

After these modifications, I'm currently in the process of pre-training the model again and measuring its performance on downstream tasks. Once I have the results, I plan to write a blog post about this work.

For the pre-training process, I'm utilizing RetroMAE.

- https://arxiv.org/abs/2211.08769
- https://github.com/FlagOpen/FlagEmbedding/tree/master/FlagEmbedding/baai_general_embedding/retromae_pretrain (impl)

> If I can help you in any way, please let me know, I'd be happy to be involved!

Thanks! I'll let you know if anything comes up!

**Comment by hotchpotch** [comment]
I wasn't familiar with the RTD (Replaced Token Detection) pre-training method. Thank you, this has deepened my understanding.

- https://arxiv.org/abs/2003.10555

**Pull request merged**
